### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/Acacia#1]
# Development
* [x] Clone the required repos
* [x] Compile tree-sitter. (**Upd.:** globbed into server compiling)
    * [x] ... and figure out where it's used - and if code needs to be written around it. **Upd.:** Has to be compiled, and we dynamically load the grammars 
* [x] Compile grammars (I guess? Figure out if it's needed)
    * [x] ... and if they need to be compiled, figure out how that works out with TS itself needing compiling (read: how are grammars loaded?). **Upd.:** They are compiled; see the "Compile tree-sitter" point
* [x] Figure out the dependency requirements
* [ ] Link all the supported parsers to the list
* [x] Figure out installing and removing parsers
* [ ] Update system
* [ ] Figure out how tree-sitter is used:
    * [x] Async
    * [x] Link to Vim
    * [ ] Get results for file
    * [ ] Apply the results to highlighting
    * [ ] Test portability
* [ ] Set up highlighting and other tree-sitter features
* [ ] Set up indentation
* [ ] Folding
* [ ] Expand the list of TODOs
* [x] nvim-treesitter is under Apache 2.0 - maybe borrow queries from them to save rewriting? (as in, add a submodule and add a symbolic link to the queries). **Upd.:** Will borrow queries for the near foreseeable future. Can rewrite if the project gains traction (or when I just get everything operational), but until then, I need working queries to get the rest of the plugin to work
* [ ] Add all the parsers

# Patching
* [x] Make sure `g:TreesitterDirectory` exists when it's needed

# Side-quests 
that I won't be investigating, and that therefore won't be implemented unless someone else takes point:
* [ ] Windows support

# Optimizations

Stuff to do when other stuff has been implemented
* [x] Cache the files
    * [x] ... and only send updated lines
    * Note: not doing any caching. The overhead is minimal and reparsing is Vim's strategy. Tree caching may be a good idea, but that's down the line
* [x] Figure out how to better share stuff between instances of vim

# Late-stage features

* [ ] Custom queries (user queries should take priority over automatic ones; not sure how to do that. `rtp` or whatever and built-in methods may be applicable?)

# Implementation languages
Vimscript as far as possible, C++ for the rest or where it makes more sense than Vimscript.

**Comment by LunarWatcher** [comment]
## Current status:

* Server interface complete
* Parser compilation done
* Linking the parsers done

## Notes

* Tree-sitter compiling is a part of the binary compiling, and is managed through Conan. This should also make updates easy in the future
* Grammars need to be compiled, so we also need an update system. Neovim's approach is dynamic libraries, and I feel that makes sense.
  * Caching is desired as well; not sure how I'm gonna structure that yet, but it depends on whether the binaries need to be kept connected or not. I imagine they do; not that it really matters

* Windows status remains unknown; there's no sockets, so the main breaking parts is the use of Git, which often lies outside the PATH, and possibly compilers.
* ... and on that note; the exact compilation process for the grammars is unclear. I can't find any buildscripts, so I assume it's manual. Which is mildly ridiculous, but hey, not my problem
  * Also not sure how the parsers orient themselves towards tree-sitter; particularly, how do I fill in the holes in `runtime.h`?
